# Generated by Django 3.0.8 on 2021-05-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210507_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donations',
            old_name='eqi_id',
            new_name='eqiid',
        ),
        migrations.RenameField(
            model_name='donations',
            old_name='ngo_id',
            new_name='ngoid',
        ),
        migrations.RenameField(
            model_name='donations',
            old_name='user_id',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='requirements',
            old_name='eqi_id',
            new_name='eqiid',
        ),
        migrations.RenameField(
            model_name='requirements',
            old_name='ngo_id',
            new_name='ngoid',
        ),
    ]
