# Generated by Django 3.0.8 on 2021-05-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210507_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngo',
            old_name='user_ngo',
            new_name='user',
        ),
    ]
